### ISSUE TITLE
Question about providing the latest emojis

### ISSUE THREAD

**Issue by HongDuHyeon** [WoodburyShortridge/rn-emoji-picker#12]
I have been using your React Native emoji picker and I believe it's the best available. 
Thank you for creating it. 

However, I've noticed that there aren't updates for the latest emojis compatible with iPhone or Android. Is there an update planned soon? If not, is there a way I could contribute? 
I am eager to provide users with the latest emojis, which is why I am reaching out

**Comment by dprevost-LMI** [comment]
Interesting question, sounds like a deal breaker to use or not this library...
