### ISSUE TITLE
Emoji selection is very slow

### ISSUE THREAD

**Issue by timothyerwin** [WoodburyShortridge/rn-emoji-picker#6]
I haven't looked at the code, but when choosing different categories there is a very noticeable delay when changing sheets.

**Comment by woodybury** [comment]
@timothyerwin how slow are we talking? It's an expensive render w/ such a large list in each section but I see delays acceptable with general UX:
https://github.com/woodybury/rn-emoji-picker/assets/24487544/8a66ab14-6460-4803-bde4-fff465fc13d7

I have been toying with the idea of adding an optional FlatListProvider prop such that you can pass in https://shopify.github.io/flash-list/ which has a lot of optimizations

**Comment by timothyerwin** [comment]
@woodybury thanks for the response. I would say ~1s...not extreme but didn't feel like a native one. I did end up finding another one which worked pretty well for what I needed. the other caveat is that I was in the simulator on a slower macbook but this other one performs fine.

perhaps you could reference it. https://github.com/mufaddalhamidofficial/react-native-emoji-keyboard

**Comment by woodybury** [comment]
@timothyerwin 1s is bad! though it sounds like it may be your dev setup. I use this in production with no complaints. However there should be headroom for more performant rendering so I'll leave this open and explore the FlatListProvider prop idea. Thanks!

**Comment by timothyerwin** [comment]
yeah, maybe in release mode without a debugger running it would be much faster. 

also, I'm not well versed enough to know but it seems like it would be better if the component loaded all the icons upfront instead of lazy loading so that the tab switching is fast. it might involve some clever hack like loading the component in the background during app startup or something...

not sure if a flatlist with virtual rendering or something is enough, but if you say it's already working fine then it could just be my setup.

**Comment by woodybury** [comment]
yes preloading the offscreen lists is probably what your comp is doing but thats hiding the performance issue instead of fixing it. I'm going to try to flashlist solution this weekend. Also see this previous discussion: https://github.com/woodybury/rn-emoji-picker/issues/2
